language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-bcbbd656
    - android-sdk-license-598b93a6
    - '.*intel.+'

script: gradle build